# This workflow will do a clean install of node dependencies and run tests
name: coverage

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          # cache-dependency-path: pnpm-lock.yaml

      - run: pnpm install --frozen-lockfile
      - run: pnpm test

      # Coverage badges will be updated on any branch except protected
      # branches 'develop' and 'main' and on a pull requests
      - name: Test angular action
        uses: emibcn/clover-coverage-badges-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # coverage-summary-path: './coverage/coverage-summary.json'
          protected-branches: '["main",  "develop"]'
          badges-directory: './.github/badges'

  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageCommand: pnpm test
